# -*- coding: utf-8 -*-
"""BTC_Dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15DpmPiHWUeZ-uXFJib2Nx7AUaye37746
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# """
# Bitcoin ETF Approval — Market Integration Dashboard
# New Finance Research Group | The Hague University of Applied Sciences
# Supervisor: Dr. Mourey Mathis | June 2026
# """
# 
# import streamlit as st
# import pandas as pd
# import numpy as np
# import plotly.graph_objects as go
# import plotly.express as px
# from plotly.subplots import make_subplots
# import yfinance as yf
# from statsmodels.tsa.api import VAR
# from statsmodels.tsa.stattools import adfuller, kpss
# from scipy import stats as scipy_stats
# from datetime import timedelta
# import warnings
# warnings.filterwarnings("ignore")
# 
# st.set_page_config(page_title="Bitcoin ETF Market Integration", page_icon="₿", layout="wide", initial_sidebar_state="expanded")
# 
# st.markdown("""<style>
# .main-header{font-size:2rem;font-weight:700;color:#1F3864;margin-bottom:0.2rem;}
# .sub-header{font-size:1rem;color:#666;margin-bottom:2rem;}
# .metric-card{background:#F0F4FA;border-radius:10px;padding:1rem 1.2rem;margin:0.3rem 0;}
# .metric-label{font-size:0.78rem;color:#888;text-transform:uppercase;letter-spacing:0.05em;}
# .metric-value{font-size:1.6rem;font-weight:700;color:#1F3864;}
# .metric-delta{font-size:0.85rem;}
# .finding-box{border-left:4px solid #2E5496;background:#F7F9FC;padding:0.8rem 1rem;border-radius:0 8px 8px 0;margin:0.5rem 0;}
# .finding-title{font-weight:600;color:#1F3864;font-size:0.95rem;}
# .finding-text{color:#444;font-size:0.88rem;line-height:1.6;}
# </style>""", unsafe_allow_html=True)
# 
# APPROVAL=pd.Timestamp("2024-01-10")
# N=141;H=10;LAGS=1
# CLASS_ORDER=["bond","commodity","equity","crypto"]
# TICKERS_BY_CLASS={"bond":["LQD"],"commodity":["GC=F"],"equity":["^GSPC"],"crypto":["BTC-USD"]}
# ALL_TICKERS=[t for c in CLASS_ORDER for t in TICKERS_BY_CLASS[c]]
# TICKER_TO_CLASS={t:c for c,ts in TICKERS_BY_CLASS.items() for t in ts}
# TICKER_LABELS={"LQD":"LQD (Bond)","GC=F":"GC=F (Gold)","^GSPC":"^GSPC (S&P 500)","BTC-USD":"BTC-USD (Bitcoin)"}
# COLORS={"before":"#1f77b4","after":"#d62728","bond":"#4C72B0","commodity":"#DD8452","equity":"#55A868","crypto":"#C44E52"}
# 
# @st.cache_data(show_spinner=False)
# def load_data():
#     def get_cal(s,e):
#         sp=yf.download("^GSPC",start=s,end=e,progress=False,auto_adjust=False)
#         return sp.index.normalize()
#     def wb(ev,n,cal,side):
#         t0=cal.searchsorted(ev,side="left")
#         if side=="pre":
#             si=max(0,t0-n);return cal[si],cal[t0-1]
#         ei=min(len(cal)-1,t0+n);return cal[t0+1],cal[ei]
#     fs=(APPROVAL-timedelta(days=int(N*1.6)+60)).strftime("%Y-%m-%d")
#     fe=(APPROVAL+timedelta(days=int(N*1.6)+60)).strftime("%Y-%m-%d")
#     cal=get_cal(fs,fe)
#     ps,pe=wb(APPROVAL,N,cal,"pre")
#     qs,qe=wb(APPROVAL,N,cal,"post")
#     df=yf.download(ALL_TICKERS,start=ps.strftime("%Y-%m-%d"),end=(qe+timedelta(days=1)).strftime("%Y-%m-%d"),progress=False,auto_adjust=True,group_by="column")
#     prices=df["Close"] if isinstance(df.columns,pd.MultiIndex) else df[["Close"]]
#     prices=prices.reindex(columns=ALL_TICKERS)
#     tgt=cal[(cal>=prices.index.min())&(cal<=prices.index.max())]
#     prices=prices.reindex(tgt).ffill(limit=3)
#     def rets(s,e):return prices.loc[s:e].pct_change().dropna(how="any")
#     return {"before_approval":rets(ps,pe),"after_approval":rets(qs,qe)},ps,pe,qs,qe
# 
# @st.cache_data(show_spinner=False)
# def run_models(_reg):
#     def fv(r):
#         d=r[ALL_TICKERS].values*100.0;return VAR(d).fit(maxlags=LAGS,ic=None)
#     res={n:fv(d) for n,d in _reg.items()}
#     irfs={n:r.irf(H) for n,r in res.items()}
#     fevds={n:r.fevd(H) for n,r in res.items()}
#     def agg(dc):
#         n=len(ALL_TICKERS);H_=dc.shape[1]
#         si=np.zeros((n,len(CLASS_ORDER)))
#         for j,t in enumerate(ALL_TICKERS):si[j,CLASS_ORDER.index(TICKER_TO_CLASS[t])]=1.0
#         ag=np.einsum("ehj,jc->ehc",dc,si);out={}
#         for c in CLASS_ORDER:
#             rows=[i for i,t in enumerate(ALL_TICKERS) if TICKER_TO_CLASS[t]==c]
#             out[c]=pd.DataFrame(ag[rows].mean(axis=0),index=range(H_),columns=CLASS_ORDER)
#         return out
#     fa={n:agg(f.decomp) for n,f in fevds.items()}
#     return res,irfs,fevds,fa
# 
# @st.cache_data(show_spinner=False)
# def run_stat(_reg):
#     rows=[]
#     for rn,r in _reg.items():
#         for t in ALL_TICKERS:
#             s=r[t].dropna()
#             as_,ap,*_=adfuller(s,autolag="AIC")
#             ks,kp,*_=kpss(s,regression="c",nlags="auto")
#             rows.append({"Asset":t,"Regime":rn.replace("_"," ").title(),"ADF stat":round(as_,4),"ADF p":round(ap,4),"KPSS stat":round(ks,4),"KPSS p":round(kp,4),"Result":"Stationary" if ap<0.05 and kp>0.05 else "Check"})
#     return pd.DataFrame(rows)
# 
# @st.cache_data(show_spinner=False)
# def run_chow(_reg,_res):
#     pa=_reg["before_approval"][ALL_TICKERS].values*100.0
#     qa=_reg["after_approval"][ALL_TICKERS].values*100.0
#     fa=np.vstack([pa,qa]);fr=VAR(fa).fit(maxlags=LAGS,ic=None)
#     pr=_res["before_approval"];qr=_res["after_approval"]
#     rf=float(np.sum(fr.resid**2));rp=float(np.sum(pr.resid**2));rq=float(np.sum(qr.resid**2))
#     neqs=len(ALL_TICKERS);kt=(neqs*LAGS+1)*neqs;nf=pr.nobs+qr.nobs
#     cf=((rf-(rp+rq))/kt)/((rp+rq)/(nf-2*kt))
#     d1=kt;d2=nf-2*kt;pv=float(1-scipy_stats.f.cdf(cf,d1,d2))
#     return {"F":round(cf,4),"df1":d1,"df2":d2,"p":round(pv,4),"n_pre":pr.nobs,"n_post":qr.nobs}
# 
# with st.sidebar:
#     st.markdown("## ₿ BTC ETF Study\n---")
#     st.markdown("**Research Group:** New Finance\n\n**Institution:** THUAS\n\n**Supervisor:** Dr. Mourey Mathis\n\n---\n**Study Period:** Jun 2023 – Aug 2024\n\n**ETF Approval:** 10 January 2024\n\n---\n**Model:** VAR(1) · Cholesky ID\n\nH = 10 trading days\n\n139 obs per sub-period")
# 
# st.markdown('<div class="main-header">Bitcoin ETF Approval — Market Integration Dashboard</div>', unsafe_allow_html=True)
# st.markdown('<div class="sub-header">New Finance Research Group · The Hague University of Applied Sciences · June 2026</div>', unsafe_allow_html=True)
# 
# with st.spinner("Loading data and running models — about 30 seconds on first load..."):
#     regimes,ps,pe,qs,qe=load_data()
#     results,irfs,fevds,fevds_agg=run_models(regimes)
#     stat_df=run_stat(regimes)
#     chow=run_chow(regimes,results)
# 
# bi=ALL_TICKERS.index("BTC-USD");gi=ALL_TICKERS.index("^GSPC")
# fp=fevds["before_approval"].decomp;fq=fevds["after_approval"].decomp
# spb=fp[bi,-1,gi]*100;spa=fq[bi,-1,gi]*100
# cb=results["before_approval"].coefs[0][bi,gi];ca=results["after_approval"].coefs[0][bi,gi]
# 
# tabs=st.tabs(["📊 Overview","📈 Shock Transmission (IRF)","🔢 Variance Decomposition (FEVD)","🧪 Statistical Tests","💡 Implications"])
# 
# with tabs[0]:
#     st.subheader("Research Overview")
#     c1,c2,c3,c4=st.columns(4)
#     with c1:st.markdown(f'<div class="metric-card"><div class="metric-label">S&P 500 → BTC before</div><div class="metric-value">{spb:.2f}%</div><div class="metric-delta" style="color:#888;">of BTC variance explained</div></div>',unsafe_allow_html=True)
#     with c2:st.markdown(f'<div class="metric-card"><div class="metric-label">S&P 500 → BTC after</div><div class="metric-value" style="color:#d62728;">{spa:.2f}%</div><div class="metric-delta" style="color:#d62728;">▲ {spa-spb:.2f}pp increase</div></div>',unsafe_allow_html=True)
#     with c3:st.markdown(f'<div class="metric-card"><div class="metric-label">S&P 500 → BTC coef</div><div class="metric-value">{ca:+.4f}</div><div class="metric-delta" style="color:#888;">from {cb:.4f} before</div></div>',unsafe_allow_html=True)
#     with c4:st.markdown(f'<div class="metric-card"><div class="metric-label">Chow test p-value</div><div class="metric-value">{chow["p"]:.4f}</div><div class="metric-delta" style="color:#888;">F({chow["df1"]},{chow["df2"]})={chow["F"]}</div></div>',unsafe_allow_html=True)
#     st.markdown("---")
#     st.info("**Research Question:** Has the approval of spot Bitcoin ETFs in January 2024 structurally changed the magnitude and direction of return and volatility spillovers between Bitcoin and traditional financial assets (S&P 500, LQD, Gold)?")
#     c1,c2=st.columns(2)
#     with c1:
#         st.markdown('<div class="finding-box"><div class="finding-title">🔴 Integration increased — equity → BTC</div><div class="finding-text">S&P 500 contribution to BTC variance tripled from 1.32% to 4.73%. VAR coefficient reversed sign from −0.4007 to +0.0093.</div></div>',unsafe_allow_html=True)
#         st.markdown('<div class="finding-box"><div class="finding-title">🟡 BTC remained primarily self-driven</div><div class="finding-text">Bitcoin own-shock self-explanation: 94.37% before, 93.996% after. Negligible change at asset level.</div></div>',unsafe_allow_html=True)
#     with c2:
#         st.markdown('<div class="finding-box"><div class="finding-title">🟢 No systemic risk to traditional markets</div><div class="finding-text">Crypto shocks explain < 0.21% of variance in bond, equity and commodity markets in both periods.</div></div>',unsafe_allow_html=True)
#         st.markdown('<div class="finding-box"><div class="finding-title">⚪ Digital gold narrative not supported</div><div class="finding-text">Gold-Bitcoin FEVD shares remain near zero in both regimes. The two assets are diverging not converging.</div></div>',unsafe_allow_html=True)
#     st.markdown("---")
#     st.markdown("**Cumulative Returns — Study Period**")
#     ar=pd.concat([regimes["before_approval"],regimes["after_approval"]])
#     cr=(1+ar).cumprod()-1
#     fig=go.Figure()
#     ct={"LQD":"#4C72B0","GC=F":"#DD8452","^GSPC":"#55A868","BTC-USD":"#C44E52"}
#     for t in ALL_TICKERS:fig.add_trace(go.Scatter(x=cr.index,y=cr[t]*100,name=TICKER_LABELS[t],line=dict(color=ct[t],width=2)))
#     fig.add_vline(x=APPROVAL,line_dash="dash",line_color="black",line_width=2,annotation_text="ETF Approval 10 Jan 2024",annotation_position="top right")
#     fig.update_layout(height=350,margin=dict(t=20,b=40,l=50,r=20),yaxis_title="Cumulative Return (%)",xaxis_title="Date",legend=dict(orientation="h",yanchor="bottom",y=1.02),plot_bgcolor="white",paper_bgcolor="white")
#     st.plotly_chart(fig,use_container_width=True)
# 
# with tabs[1]:
#     st.subheader("Impulse Response Functions — Before vs After ETF Approval")
#     st.markdown("Select a shock asset to see how all four assets respond over 10 trading days. Blue = before approval, Red = after approval.")
#     sl=st.selectbox("Shock asset",[TICKER_LABELS[t] for t in ALL_TICKERS],index=2,key="ss")
#     st=[t for t in ALL_TICKERS if TICKER_LABELS[t]==sl][0];j=ALL_TICKERS.index(st)
#     fig=make_subplots(rows=2,cols=2,subplot_titles=[TICKER_LABELS[t] for t in ALL_TICKERS])
#     pos=[(1,1),(1,2),(2,1),(2,2)];hr=list(range(H+1))
#     for idx,ticker in enumerate(ALL_TICKERS):
#         i=ALL_TICKERS.index(ticker);row,col=pos[idx]
#         for rg,color,name in [("before_approval",COLORS["before"],"Before ETF"),("after_approval",COLORS["after"],"After ETF")]:
#             orth=irfs[rg].orth_irfs
#             fig.add_trace(go.Scatter(x=hr,y=orth[:,i,j].tolist(),name=name,line=dict(color=color,width=2.5),showlegend=(idx==0),legendgroup=name),row=row,col=col)
#         fig.add_hline(y=0,line_dash="dot",line_color="gray",line_width=1,row=row,col=col)
#     fig.update_layout(height=520,margin=dict(t=40,b=40,l=40,r=20),plot_bgcolor="white",paper_bgcolor="white",legend=dict(orientation="h",yanchor="bottom",y=1.03),title_text=f"Response to shock: {sl}",title_font_size=14)
#     fig.update_xaxes(title_text="h (days)",showgrid=True,gridcolor="#eee")
#     fig.update_yaxes(showgrid=True,gridcolor="#eee")
#     st.plotly_chart(fig,use_container_width=True)
#     interp={"LQD (Bond)":"Bond markets show near-zero response to all shocks in both regimes — confirming structural insulation of fixed-income markets.","GC=F (Gold)":"Gold shows marginally larger responses to equity shocks post-ETF. The Gold-Bitcoin relationship remains near zero — challenging the digital gold narrative.","^GSPC (S&P 500)":"Equity markets show near-zero response to Bitcoin shocks in both periods — confirming the directional asymmetry. S&P 500 became more self-driven post-ETF (+11.91pp).","BTC-USD (Bitcoin)":"HEADLINE FINDING: Before ETF, Bitcoin's response to S&P 500 shocks is near zero. After approval, a positive response appears at h=0 and h=1. Coefficient reversed from −0.4007 to +0.0093."}
#     st.info(interp.get(sl,""))
# 
# with tabs[2]:
#     st.subheader("Forecast Error Variance Decomposition")
#     s1,s2,s3=st.tabs(["Asset-Level Diagonal","Full 4×4 Matrix","Class-Level (Table 1)"])
#     with s1:
#         st.markdown("**Own-shock self-explanation at H=10**")
#         dd=[]
#         for i,t in enumerate(ALL_TICKERS):
#             b=fp[i,-1,i]*100;a=fq[i,-1,i]*100
#             dd.append({"Asset":TICKER_LABELS[t],"Before ETF (%)":round(b,4),"After ETF (%)":round(a,4),"Change (pp)":round(a-b,4)})
#         ddf=pd.DataFrame(dd)
#         fig=go.Figure()
#         fig.add_trace(go.Bar(name="Before ETF",x=ddf["Asset"],y=ddf["Before ETF (%)"],marker_color=COLORS["before"],opacity=0.85))
#         fig.add_trace(go.Bar(name="After ETF",x=ddf["Asset"],y=ddf["After ETF (%)"],marker_color=COLORS["after"],opacity=0.85))
#         fig.update_layout(barmode="group",height=380,margin=dict(t=20,b=40,l=50,r=20),yaxis_title="Own-shock share (%)",yaxis_range=[60,105],plot_bgcolor="white",paper_bgcolor="white",legend=dict(orientation="h",yanchor="bottom",y=1.02))
#         st.plotly_chart(fig,use_container_width=True)
#         st.dataframe(ddf.style.format({"Before ETF (%)":"{:.4f}","After ETF (%)":"{:.4f}","Change (pp)":"{:+.4f}"}),use_container_width=True,hide_index=True)
#     with s2:
#         st.markdown("**Full 4×4 FEVD matrix at H=10**")
#         rc=st.radio("Regime",["Before ETF approval","After ETF approval"],horizontal=True,key="fr")
#         rk="before_approval" if "Before" in rc else "after_approval"
#         ds=fevds[rk].decomp
#         mx=pd.DataFrame(ds[:,-1,:]*100,index=[TICKER_LABELS[t] for t in ALL_TICKERS],columns=[TICKER_LABELS[t] for t in ALL_TICKERS]).round(4)
#         fig=px.imshow(mx,text_auto=".2f",color_continuous_scale="Blues",aspect="auto",height=380,labels=dict(x="Shock asset",y="Response asset",color="Share (%)"))
#         fig.update_layout(margin=dict(t=20,b=20,l=20,r=20))
#         st.plotly_chart(fig,use_container_width=True)
#         st.caption("Diagonal = own-shock. Off-diagonal = cross-asset transmission.")
#     with s3:
#         st.markdown("**Crypto shock transmission to traditional markets (Table 1)**")
#         td={"Response Class":["Bond","Commodity","Equity","Crypto"],"Before Approval":[0.0009,0.0003,0.0020,0.7953],"After Approval":[0.0002,0.0010,0.0021,0.8492],"Change":[-0.0007,0.0006,0.0001,0.0539]}
#         tdf=pd.DataFrame(td)
#         fig=go.Figure()
#         cc=[COLORS["bond"],COLORS["commodity"],COLORS["equity"],COLORS["crypto"]]
#         for i,row in tdf.iterrows():fig.add_trace(go.Bar(name=row["Response Class"],x=["Before Approval","After Approval"],y=[row["Before Approval"],row["After Approval"]],marker_color=cc[i]))
#         fig.update_layout(barmode="group",height=380,margin=dict(t=20,b=40,l=60,r=20),yaxis_title="Share of forecast error variance",plot_bgcolor="white",paper_bgcolor="white",legend=dict(orientation="h",yanchor="bottom",y=1.02))
#         st.plotly_chart(fig,use_container_width=True)
#         st.dataframe(tdf.style.format({"Before Approval":"{:.4f}","After Approval":"{:.4f}","Change":"{:+.4f}"}),use_container_width=True,hide_index=True)
#         st.caption("Changes in non-crypto rows are economically negligible (< 0.21%). Main finding: S&P 500 → BTC tripled from 1.32% to 4.73%.")
# 
# with tabs[3]:
#     st.subheader("Statistical Tests")
#     c1,c2=st.columns(2)
#     with c1:
#         st.markdown("**Stationarity Tests — ADF and KPSS**")
#         st.dataframe(stat_df.style.applymap(lambda v:"background-color:#d4edda;color:#155724;" if v=="Stationary" else "background-color:#fff3cd;color:#856404;",subset=["Result"]).format({"ADF stat":"{:.4f}","ADF p":"{:.4f}","KPSS stat":"{:.4f}","KPSS p":"{:.4f}"}),use_container_width=True,hide_index=True)
#         if all(stat_df["Result"]=="Stationary"):st.success("✓ All series confirmed stationary. VAR estimation is valid.")
#         else:st.warning("⚠ Some series need review.")
#         st.markdown("**Lag Selection — AIC and BIC**")
#         lr=[]
#         for rn,r in regimes.items():
#             d=r[ALL_TICKERS].values*100.0
#             for p in range(1,6):
#                 try:
#                     rp=VAR(d).fit(maxlags=p,ic=None)
#                     lr.append({"Regime":rn.replace("_"," ").title(),"Lag":p,"AIC":round(rp.aic,4),"BIC":round(rp.bic,4),"Selected":"✓" if p==LAGS else ""})
#                 except:pass
#         ldf=pd.DataFrame(lr)
#         st.dataframe(ldf.style.applymap(lambda v:"background-color:#d4edda;color:#155724;font-weight:bold;" if v=="✓" else "",subset=["Selected"]).format({"AIC":"{:.4f}","BIC":"{:.4f}"}),use_container_width=True,hide_index=True)
#     with c2:
#         st.markdown("**Chow Structural Break Test**")
#         cs="Not rejected" if chow["p"]>0.05 else "Rejected at 5%"
#         cc="#fff3cd" if chow["p"]>0.05 else "#d4edda"
#         ctc="#856404" if chow["p"]>0.05 else "#155724"
#         st.markdown(f'<div style="background:{cc};border-radius:8px;padding:1.2rem;margin-bottom:1rem;"><div style="font-size:0.85rem;color:{ctc};font-weight:600;margin-bottom:0.8rem;">Breakpoint: 10 January 2024</div><table style="width:100%;font-size:0.88rem;color:{ctc};"><tr><td><b>Pre-ETF obs</b></td><td>{chow["n_pre"]}</td></tr><tr><td><b>Post-ETF obs</b></td><td>{chow["n_post"]}</td></tr><tr><td><b>F-statistic</b></td><td>{chow["F"]}</td></tr><tr><td><b>Degrees of freedom</b></td><td>({chow["df1"]}, {chow["df2"]})</td></tr><tr><td><b>P-value</b></td><td>{chow["p"]}</td></tr><tr><td><b>H₀ result</b></td><td><b>{cs}</b></td></tr></table></div>',unsafe_allow_html=True)
#         st.markdown("**Interpretation:** The system-wide Chow test fails to reject parameter stability (p=0.9967). This does **not** mean no change occurred — the test has low power when change is concentrated in a single channel (S&P 500 → BTC). The directional evidence remains: FEVD share tripled (1.32%→4.73%) and the coefficient reversed sign (−0.40→+0.01).")
#         st.markdown("**Key coefficient: S&P 500 lag 1 → BTC**")
#         st.dataframe(pd.DataFrame({"Regime":["Before ETF","After ETF"],"Coefficient":[round(cb,6),round(ca,6)],"Direction":["Negative (counter-cyclical)","Positive (co-movement)"]}),use_container_width=True,hide_index=True)
# 
# with tabs[4]:
#     st.subheader("Implications for Stakeholders")
#     c1,c2,c3=st.columns(3)
#     with c1:
#         st.markdown("### 💼 Portfolio Managers")
#         st.markdown(f"**S&P 500 → BTC contribution: {spb:.2f}% → {spa:.2f}%**\n\nBitcoin's sensitivity to equity shocks more than tripled. The VAR coefficient reversed from {cb:.4f} to {ca:.4f}. Bitcoin now moves *with* equities during stress — weakening its diversification case. Reconsider Bitcoin allocation weights in multi-asset portfolios.")
#     with c2:
#         st.markdown("### 🏦 Regulators")
#         st.markdown("**Crypto → traditional markets: < 0.21%**\n\nBond exposure to crypto fell from 0.09% to 0.02%. Equity exposure is essentially unchanged at ~0.21%. Systemic contagion from crypto to traditional markets has not materialised within the study window — tentatively reassuring for financial stability.")
#     with c3:
#         st.markdown("### 📐 ETF Designers")
#         st.markdown("**One-directional integration channel**\n\nEquity → BTC strengthened. BTC → Equity unchanged. Gold → BTC near zero. This pattern provides an empirical baseline for predicting Ethereum ETF integration consequences. The May 2024 Ethereum approval is the next event to test with this same framework.")
#     st.markdown("---")
#     st.markdown("""<div style="background:#F0F4FA;border-radius:10px;padding:1.5rem;border-left:5px solid #1F3864;">
#     <div style="font-size:1rem;color:#1F3864;font-weight:600;margin-bottom:0.8rem;">Central Conclusion — Asymmetric Integration</div>
#     <div style="color:#333;line-height:1.8;font-size:0.95rem;">
#     The Bitcoin spot ETF approval of January 2024 <b>asymmetrically changed</b> market integration. The equity-to-Bitcoin linkage tightened — S&P 500 variance contribution to BTC tripled (1.32%→4.73%) and the coefficient reversed sign (−0.4007→+0.0093) — while traditional markets remained insulated from crypto-specific dynamics. Bitcoin has transitioned toward a <b>conventional risk asset</b> that moves with equities, weakening its diversification case without creating systemic risk.
#     </div></div>""", unsafe_allow_html=True)
#     st.markdown("---")
#     st.caption("Bitcoin ETF Approval and Crypto–Traditional Market Integration | New Finance Research Group | THUAS 2026 | Supervisor: Dr. Mourey Mathis")